### ISSUE TITLE
build fails reference to packed field is unaligned

### ISSUE THREAD

**Issue by randomuygvruyv65423654** [system76/firmware-setup#39]
[log.txt](https://github.com/system76/firmware-setup/files/14842941/log.txt)
Build fails for firmware-setup module. Standard out attached in log.txt. Looks like the fatal error is "reference to packed field is unaligned src/serial.rs:79:9"
Debian 12 6.1.0-18-amd64
steps to failure message
1. ./scripts/install-deps.sh
2. . ~/.cargo/env
3. ./scripts/build.sh galp5

**Comment by crawfxrd** [comment]
See: #35
Blocks: #36

But something still seems wrong with the environment. It should be using nightly-2023-01-21, but these errors are from using a newer toolchain.

**Comment by randomuygvruyv65423654** [comment]
I blew away my .rustup and .cargo and reinstalled from scratch. It builds correctly now so I think you are right about the environment.
